# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/game_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 700)
        self.registration = QtWidgets.QPushButton(Form)
        self.registration.setGeometry(QtCore.QRect(230, 270, 131, 91))
        self.registration.setText("")
        self.registration.setObjectName("registration")
        self.levels_button = QtWidgets.QPushButton(Form)
        self.levels_button.setGeometry(QtCore.QRect(430, 270, 131, 91))
        self.levels_button.setText("")
        self.levels_button.setObjectName("levels_button")
        self.creation_new_levels = QtWidgets.QPushButton(Form)
        self.creation_new_levels.setGeometry(QtCore.QRect(620, 270, 131, 91))
        self.creation_new_levels.setText("")
        self.creation_new_levels.setObjectName("creation_new_levels")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
